<?php

use Sprout\Console\GenerateEditorExportsCommand;

it('builds export names from slugs', function () {
    $command = new GenerateEditorExportsCommand;

    expect($command->exportNameFromSlug('button'))->toBe('Button')
        ->and($command->exportNameFromSlug('grid-column'))->toBe('GridColumn')
        ->and($command->exportNameFromSlug('half-container'))->toBe('HalfContainer');
});

it('builds a dumb module that imports createExport from @sprout/runtime', function () {
    $command = new GenerateEditorExportsCommand;

    $module = $command->buildModule([
        'alert' => 'Alert',
        'button' => 'Button',
    ]);

    expect($module)->toContain("import { createExport } from '@sprout/runtime';")
        ->and($module)->toContain("export const Alert = createExport('alert');")
        ->and($module)->toContain("export const Button = createExport('button');")
        ->and($module)->not->toContain('export function getComponent')
        ->and($module)->toContain('Auto-generated by `sprout:generate-editor-exports`');
});

it('builds typescript declarations from manifest component metadata', function () {
    $command = new GenerateEditorExportsCommand;

    $types = $command->buildTypes([
        'button' => [
            'exportName' => 'Button',
            'class' => 'App\\View\\Components\\Ui\\Button',
            'props' => [
                ['name' => 'size', 'type' => 'string', 'default' => 'md', 'required' => false],
                ['name' => 'arrow', 'type' => 'bool', 'default' => false, 'required' => false],
            ],
        ],
    ]);

    expect($types)->toContain('export type ButtonProps')
        ->and($types)->toContain('size?: string;')
        ->and($types)->toContain('arrow?: boolean;')
        ->and($types)->toContain('export declare const Button: ComponentType<ButtonProps>;');
});
