<?php

namespace Sprout\Tests;

use PHPUnit\Framework\TestCase;
use Sprout\Console\GenerateEditorExportsCommand;

class GenerateEditorExportsCommandTest extends TestCase
{
    public function test_export_name_from_slug(): void
    {
        $command = new GenerateEditorExportsCommand;

        $this->assertSame('Button', $command->exportNameFromSlug('button'));
        $this->assertSame('GridColumn', $command->exportNameFromSlug('grid-column'));
        $this->assertSame('HalfContainer', $command->exportNameFromSlug('half-container'));
    }

    public function test_build_module_includes_exports(): void
    {
        $command = new GenerateEditorExportsCommand;

        $module = $command->buildModule([
            'alert' => 'Alert',
            'button' => 'Button',
        ]);

        $this->assertStringContainsString('export function getComponent(name)', $module);
        $this->assertStringContainsString("export const Alert = getComponent('alert');", $module);
        $this->assertStringContainsString("export const Button = getComponent('button');", $module);
        $this->assertStringContainsString('Auto-generated by `wp acorn sprout:generate-editor-exports`', $module);
    }
}
