<?php

use Illuminate\Support\Facades\File;
use Parity\Contracts\Host;
use Parity\Host\LaravelHost;
use Parity\Schema\Version;
use Parity\Tests\Support\FakeHost;

beforeEach(function () {
    $this->outputRelative = 'storage/framework/parity-tests/'.uniqid('run_', true);
    File::ensureDirectoryExists(base_path($this->outputRelative));

    config([
        'parity.components.path' => __DIR__.'/fixtures',
        'parity.components.namespace' => 'Parity\\Tests\\Fixtures',
        'parity.editor.manifest_path' => $this->outputRelative.'/manifest.json',
    ]);
});

afterEach(function () {
    $path = base_path($this->outputRelative ?? '');

    if ($path !== base_path() && File::isDirectory($path)) {
        File::deleteDirectory($path);
    }
});

it('writes a committed manifest with reflected constructor props', function () {
    $this->artisan('parity:manifest')
        ->assertSuccessful();

    $path = base_path($this->outputRelative.'/manifest.json');

    expect($path)->toBeFile();

    $manifest = json_decode(File::get($path), true, 512, JSON_THROW_ON_ERROR);

    expect($manifest['schemaVersion'])->toBe(Version::CURRENT)
        ->and($manifest['components'])->toHaveKey('reflect-props-test')
        ->and($manifest['components']['reflect-props-test']['exportName'])->toBe('ReflectPropsTest')
        ->and($manifest['components']['reflect-props-test']['class'])->toBe(
            'Parity\\Tests\\Fixtures\\ReflectPropsTestComponent'
        )
        ->and($manifest['components']['reflect-props-test']['props'])->toContain([
            'name' => 'size',
            'type' => 'string',
            'default' => 'md',
            'required' => false,
        ]);
});

it('fails doctor when the manifest drifts from discovered schemas', function () {
    $manifestPath = base_path($this->outputRelative.'/manifest.json');
    File::put($manifestPath, json_encode([
        'generatedAt' => now()->toIso8601String(),
        'schemaVersion' => Version::CURRENT,
        'components' => [
            'shell-structure-test' => [
                'exportName' => 'ShellStructureTest',
                'class' => 'Parity\\Tests\\Fixtures\\ShellStructureTestComponent',
                'props' => [],
            ],
        ],
    ], JSON_THROW_ON_ERROR));

    $this->artisan('parity:doctor')
        ->assertFailed();
});

it('warns when discovered schemas reference undefined presets', function () {
    config([
        'parity.presets' => [],
        'parity.editor.manifest_path' => $this->outputRelative.'/missing-manifest.json',
    ]);

    $this->artisan('parity:doctor')
        ->expectsOutputToContain('undefined preset "cols"')
        ->assertFailed();
});

it('resolves safelist output through the laravel host base path', function () {
    expect(app(Host::class))->toBeInstanceOf(LaravelHost::class);

    $relative = $this->outputRelative.'/safelist.css';
    $path = base_path($relative);

    $this->artisan('parity:safelist', ['--output' => $relative])
        ->assertSuccessful();

    expect($path)->toBeFile()
        ->and(File::get($path))->toContain('Auto-generated by parity:safelist');
});

it('uses fake host path resolution for adapter doubles', function () {
    $host = new FakeHost('/var/theme');

    expect($host->path('resources/js/parity/manifest.json'))
        ->toBe('/var/theme/resources/js/parity/manifest.json')
        ->and($host->escUrl('media/a.png'))->toBe('https://example.test/media/a.png')
        ->and($host->filter('parity/test', 'x'))->toBe('x');

    $host->listen('parity/test', fn ($value) => $value.'-y');

    expect($host->filter('parity/test', 'x'))->toBe('x-y');
});
