import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import { afterEach, describe, expect, it, vi } from 'vitest';
import parity, {
    RESOLVED_VIRTUAL_ID,
    buildModule,
    buildTypes,
    checkManifest,
    emptyModule,
    slugToExportMap,
} from '../../vite.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sageRoot = path.join(__dirname, 'fixtures/sage');
const laravelRoot = path.join(__dirname, 'fixtures/laravel');
const packageRoot = path.resolve(__dirname, '../..');
const runtimePath = path.join(packageRoot, 'resources/js/editor/runtime.js');
const canvasPath = path.join(packageRoot, 'resources/js/editor/canvas.js');

function createPlugin(root, options = {}) {
    const plugin = parity({ types: false, ...options });
    const warnings = [];

    plugin.configResolved({
        root,
        logger: {
            warn: (message) => warnings.push(message),
        },
    });

    return { plugin, warnings };
}

describe('parity vite plugin helpers', () => {
    it('builds export names and sorted slug maps', () => {
        expect(slugToExportMap({
            'grid-column': 'GridColumn',
            alert: { exportName: 'Alert' },
            button: 'Button',
        })).toEqual({
            alert: 'Alert',
            button: 'Button',
            'grid-column': 'GridColumn',
        });
    });

    it('builds a dumb module that imports createExport from @parity/runtime', () => {
        const module = buildModule({
            alert: 'Alert',
            button: 'Button',
        });

        expect(module).toContain("import { createExport } from '@parity/runtime';");
        expect(module).toContain("export const Alert = createExport('alert');");
        expect(module).toContain("export const Button = createExport('button');");
        expect(module).not.toContain('export function getComponent');
        expect(module).toContain('Auto-generated by the Parity Vite plugin');
    });

    it('builds ambient typescript declarations from manifest metadata', () => {
        const types = buildTypes({
            button: {
                exportName: 'Button',
                class: 'App\\View\\Components\\Ui\\Button',
                props: [
                    { name: 'size', type: 'string', default: 'md', required: false },
                    { name: 'arrow', type: 'bool', default: false, required: false },
                    { name: 'label', type: 'string', default: null, required: true },
                ],
            },
        });

        expect(types).toContain("declare module '@parity/components'");
        expect(types).toContain('export type ButtonProps');
        expect(types).toContain('size?: string;');
        expect(types).toContain('arrow?: boolean;');
        expect(types).toContain('label: string;');
        expect(types).toContain('export const Button: ComponentType<ButtonProps>;');
    });
});

describe('parity vite plugin resolveId', () => {
    it.each([
        ['sage theme layout', sageRoot],
        ['laravel app layout', laravelRoot],
    ])('resolves runtime, canvas, and component ids for %s', (_label, root) => {
        const { plugin } = createPlugin(root);

        expect(plugin.resolveId('@parity/runtime')).toBe(runtimePath);
        expect(plugin.resolveId('@parity/canvas')).toBe(canvasPath);
        expect(plugin.resolveId('@parity/components')).toBe(RESOLVED_VIRTUAL_ID);
        expect(plugin.resolveId('virtual:parity/components')).toBe(RESOLVED_VIRTUAL_ID);
        expect(plugin.resolveId('something-else')).toBeNull();
    });
});

describe('parity vite plugin load', () => {
    it('loads the virtual module from the committed manifest', () => {
        const { plugin } = createPlugin(sageRoot);
        plugin.buildStart();

        const code = plugin.load(RESOLVED_VIRTUAL_ID);

        expect(code).toContain("export const Alert = createExport('alert');");
        expect(code).toContain("export const Button = createExport('button');");
        expect(code).toContain("export const GridColumn = createExport('grid-column');");
        expect(code.indexOf("export const Alert")).toBeLessThan(code.indexOf("export const Button"));
    });

    it('serves an empty module when the manifest is missing', () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-missing-'));
        const { plugin, warnings } = createPlugin(tempRoot);

        plugin.buildStart();
        const code = plugin.load(RESOLVED_VIRTUAL_ID);

        expect(code).toBe(emptyModule());
        expect(warnings.some((message) => message.includes('Manifest not found'))).toBe(true);

        fs.rmSync(tempRoot, { recursive: true, force: true });
    });

    it('warns and serves an empty module when the manifest is unparseable', () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-bad-'));
        const manifestDir = path.join(tempRoot, 'resources/js/parity');
        fs.mkdirSync(manifestDir, { recursive: true });
        fs.writeFileSync(path.join(manifestDir, 'manifest.json'), '{not-json');

        const { plugin, warnings } = createPlugin(tempRoot);
        plugin.buildStart();
        const code = plugin.load(RESOLVED_VIRTUAL_ID);

        expect(code).toBe(emptyModule());
        expect(warnings.some((message) => message.includes('unparseable'))).toBe(true);

        fs.rmSync(tempRoot, { recursive: true, force: true });
    });

    it('warns when the manifest is older than a component php file', () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-stale-'));
        const manifestDir = path.join(tempRoot, 'resources/js/parity');
        const componentsDir = path.join(tempRoot, 'app/View/Components');
        fs.mkdirSync(manifestDir, { recursive: true });
        fs.mkdirSync(componentsDir, { recursive: true });

        const manifestPath = path.join(manifestDir, 'manifest.json');
        fs.writeFileSync(manifestPath, JSON.stringify({
            generatedAt: '2020-01-01T00:00:00+00:00',
            schemaVersion: '1.0',
            components: { button: 'Button' },
        }));
        const old = new Date('2020-01-01T00:00:00Z');
        fs.utimesSync(manifestPath, old, old);

        const phpPath = path.join(componentsDir, 'Button.php');
        fs.writeFileSync(phpPath, '<?php\n');
        const newer = new Date('2026-01-01T00:00:00Z');
        fs.utimesSync(phpPath, newer, newer);

        const warnings = [];
        const result = checkManifest({
            manifestPath,
            componentsDir,
            warn: (message) => warnings.push(message),
        });

        expect(result.ok).toBe(true);
        expect(result.reason).toBe('stale');
        expect(warnings.some((message) => message.includes('older than'))).toBe(true);

        fs.rmSync(tempRoot, { recursive: true, force: true });
    });
});

describe('parity vite plugin types', () => {
    /** @type {string[]} */
    const temps = [];

    afterEach(() => {
        for (const dir of temps.splice(0)) {
            fs.rmSync(dir, { recursive: true, force: true });
        }
    });

    it('writes ambient declarations next to the project root', () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-types-'));
        temps.push(tempRoot);

        fs.cpSync(sageRoot, tempRoot, { recursive: true });

        const typesPath = path.join(tempRoot, 'resources/js/parity/components.d.ts');
        const { plugin } = createPlugin(tempRoot, {
            types: 'resources/js/parity/components.d.ts',
        });

        plugin.buildStart();

        expect(fs.existsSync(typesPath)).toBe(true);
        const contents = fs.readFileSync(typesPath, 'utf8');
        expect(contents).toContain("declare module '@parity/components'");
        expect(contents).toContain('export type ButtonProps');
        expect(contents).toContain('arrow?: boolean;');
    });

    it('skips type generation when types is false', () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-notypes-'));
        temps.push(tempRoot);
        fs.cpSync(sageRoot, tempRoot, { recursive: true });

        const typesPath = path.join(tempRoot, 'resources/js/parity/components.d.ts');
        const { plugin } = createPlugin(tempRoot, { types: false });
        plugin.buildStart();

        expect(fs.existsSync(typesPath)).toBe(false);
    });
});

describe('parity vite plugin end-to-end build', () => {
    it('builds a sage fixture chunk that contains resolved exports', async () => {
        const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parity-vite-build-'));
        fs.cpSync(sageRoot, tempRoot, { recursive: true });

        const entry = path.join(tempRoot, 'entry.js');
        fs.writeFileSync(entry, "import { Alert, Button } from '@parity/components';\nexport { Alert, Button };\n");

        const outDir = path.join(tempRoot, 'dist');

        await build({
            root: tempRoot,
            logLevel: 'error',
            build: {
                outDir,
                emptyOutDir: true,
                lib: {
                    entry,
                    formats: ['es'],
                    fileName: () => 'bundle.js',
                },
                rollupOptions: {
                    external: [],
                },
            },
            plugins: [parity({ types: false })],
        });

        const bundle = fs.readFileSync(path.join(outDir, 'bundle.js'), 'utf8');
        expect(bundle).toMatch(/["']alert["']/);
        expect(bundle).toMatch(/["']button["']/);
        expect(bundle).toContain('Alert');
        expect(bundle).toContain('Button');
        expect(bundle).toMatch(/Parity\(/);

        fs.rmSync(tempRoot, { recursive: true, force: true });
    }, 30_000);
});
