/**
 * Build the virtual @parity/components ES module from a manifest.
 */

/**
 * @param {string} slug
 * @returns {string}
 */
export function exportNameFromSlug(slug) {
    return String(slug)
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

/**
 * @param {Record<string, unknown>} components
 * @returns {Record<string, string>}
 */
export function slugToExportMap(components) {
    /** @type {Record<string, string>} */
    const map = {};

    for (const [slug, meta] of Object.entries(components ?? {})) {
        if (typeof meta === 'string') {
            map[slug] = meta;
            continue;
        }

        if (meta && typeof meta === 'object' && 'exportName' in meta && meta.exportName) {
            map[slug] = String(meta.exportName);
            continue;
        }

        map[slug] = exportNameFromSlug(slug);
    }

    return Object.fromEntries(
        Object.entries(map).sort(([a], [b]) => a.localeCompare(b)),
    );
}

/**
 * @param {Record<string, string>} components
 * @returns {string}
 */
export function buildModule(components) {
    const lines = [
        '/**',
        ' * Auto-generated by the Parity Vite plugin from the committed manifest.',
        ' * Do not edit manually. Run `parity:manifest` then rebuild.',
        ' */',
        '',
        "import { createExport } from '@parity/runtime';",
        '',
    ];

    for (const [slug, exportName] of Object.entries(components)) {
        lines.push(`export const ${exportName} = createExport('${slug}');`);
    }

    lines.push('');

    return lines.join('\n');
}

/**
 * @returns {string}
 */
export function emptyModule() {
    return buildModule({});
}
