/**
 * Build ambient TypeScript declarations for @parity/components.
 */

import { exportNameFromSlug } from './module.js';

/**
 * @param {string} type
 * @returns {string}
 */
export function phpTypeToTs(type) {
    const parts = type.split('|').map((part) => part.trim());
    const mapped = parts.map((part) => {
        if (part.startsWith('?')) {
            return `${phpTypeToTs(part.slice(1))} | null`;
        }

        switch (part) {
            case 'string':
                return 'string';
            case 'int':
            case 'integer':
            case 'float':
            case 'double':
                return 'number';
            case 'bool':
            case 'boolean':
                return 'boolean';
            case 'array':
                return 'unknown[]';
            case 'null':
                return 'null';
            case 'mixed':
                return 'unknown';
            default:
                return 'unknown';
        }
    });

    return [...new Set(mapped)].join(' | ');
}

/**
 * @param {Record<string, unknown>} components
 * @returns {string}
 */
export function buildTypes(components) {
    const lines = [
        '/**',
        ' * Auto-generated by the Parity Vite plugin from the committed manifest.',
        ' * Do not edit manually.',
        ' */',
        '',
        "declare module '@parity/components' {",
        "    import type { ComponentType } from 'react';",
        '',
    ];

    /** @type {string[]} */
    const exports = [];

    for (const [slug, meta] of Object.entries(components ?? {})) {
        const exportName = typeof meta === 'string'
            ? meta
            : String(meta?.exportName ?? exportNameFromSlug(String(slug)));
        const props = typeof meta === 'object' && meta && Array.isArray(meta.props)
            ? meta.props
            : [];
        const propsType = `${exportName}Props`;

        lines.push(`    export type ${propsType} = {`);

        for (const prop of props) {
            if (! prop || typeof prop !== 'object' || ! prop.name) {
                continue;
            }

            const optional = prop.required ? '' : '?';
            const tsType = phpTypeToTs(String(prop.type ?? 'mixed'));
            lines.push(`        ${prop.name}${optional}: ${tsType};`);
        }

        lines.push('        [key: string]: unknown;');
        lines.push('    };');
        lines.push('');
        lines.push(`    export const ${exportName}: ComponentType<${propsType}>;`);
        lines.push('');

        exports.push(exportName);
    }

    if (exports.length > 0) {
        lines.push(`    export { ${exports.join(', ')} };`);
        lines.push('');
    }

    lines.push('}');
    lines.push('');

    return lines.join('\n');
}
