<?php

namespace Sprout\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Sprout\Config\ConfigCollector;

class GenerateEditorExportsCommand extends Command
{
    protected $signature = 'sprout:generate-editor-exports {--output= : Output path relative to theme root}';

    protected $description = 'Generate Sprout editor component ES module exports from PHP schemas';

    /** @var list<string> */
    protected array $reservedConfigKeys = [
        'common',
        'schemaVersion',
        'icons',
        'iconAjaxUrl',
        'iconAjaxNonce',
        'tokens',
    ];

    public function handle(ConfigCollector $collector): int
    {
        app('sprout')->discoverComponents();

        $components = [];

        foreach (array_keys($collector->all()) as $name) {
            if (in_array($name, $this->reservedConfigKeys, true)) {
                continue;
            }

            $schema = $collector->get($name);

            if (! is_array($schema) || ! isset($schema['schemaVersion'])) {
                continue;
            }

            $components[$name] = $this->exportNameFromSlug($name);
        }

        ksort($components);

        /** @var array<string, string> $components */
        $components = apply_filters('sprout/editor/export-names', $components);

        $output = $this->option('output')
            ?? config('sprout.editor.exports_path', 'resources/js/sprout/components.js');

        $path = function_exists('get_theme_file_path')
            ? get_theme_file_path($output)
            : base_path($output);

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $this->buildModule($components));

        $this->components->info('Editor exports written to '.$path.' ('.count($components).' components)');

        return self::SUCCESS;
    }

    /**
     * @param array<string, string> $components
     */
    public function buildModule(array $components): string
    {
        $lines = [
            '/**',
            ' * Auto-generated by `wp acorn sprout:generate-editor-exports`.',
            ' * Do not edit manually.',
            ' */',
            '',
            'export function getComponent(name) {',
            "    if (typeof window !== 'undefined' && window.sprout?.getComponent) {",
            '        return window.sprout.getComponent(name);',
            '    }',
            '',
            '    return function SproutComponentFallback() {',
            '        return null;',
            '    };',
            '}',
            '',
        ];

        foreach ($components as $slug => $exportName) {
            $lines[] = "export const {$exportName} = getComponent('{$slug}');";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    public function exportNameFromSlug(string $slug): string
    {
        return str_replace(' ', '', ucwords(str_replace('-', ' ', $slug)));
    }
}
