<?php

namespace Parity\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Parity\Contracts\Host;

class GenerateEditorExportsCommand extends Command
{
    protected $signature = 'parity:generate-editor-exports
        {--manifest= : Manifest path relative to the host root}
        {--output= : Exports JS path relative to the host root}
        {--types= : TypeScript declaration path relative to the host root}';

    protected $description = 'Generate Parity editor component ES module exports from the committed manifest';

    public function handle(Host $host): int
    {
        $manifestRelative = $this->option('manifest')
            ?? config('parity.editor.manifest_path', 'resources/js/parity/manifest.json');
        $manifestPath = $host->path($manifestRelative);

        if (! File::exists($manifestPath)) {
            $this->components->error("Manifest not found at {$manifestPath}. Run parity:manifest first.");

            return self::FAILURE;
        }

        /** @var array<string, mixed> $manifest */
        $manifest = json_decode(File::get($manifestPath), true, 512, JSON_THROW_ON_ERROR);
        $components = $manifest['components'] ?? [];

        if (! is_array($components) || $components === []) {
            $this->components->warn('Manifest contains no components.');
        }

        $slugToExport = [];

        foreach ($components as $slug => $meta) {
            if (is_string($meta)) {
                $slugToExport[$slug] = $meta;

                continue;
            }

            if (is_array($meta) && isset($meta['exportName'])) {
                $slugToExport[$slug] = (string) $meta['exportName'];
            }
        }

        ksort($slugToExport);

        $output = $this->option('output')
            ?? config('parity.editor.exports_path', 'resources/js/parity/components.js');
        $types = $this->option('types')
            ?? config('parity.editor.types_path', 'resources/js/parity/components.d.ts');

        $jsPath = $host->path($output);
        $dtsPath = $host->path($types);

        File::ensureDirectoryExists(dirname($jsPath));
        File::put($jsPath, $this->buildModule($slugToExport));

        File::ensureDirectoryExists(dirname($dtsPath));
        File::put($dtsPath, $this->buildTypes($components));

        $this->components->info('Editor exports written to '.$jsPath.' ('.count($slugToExport).' components)');
        $this->components->info('Type declarations written to '.$dtsPath);

        return self::SUCCESS;
    }

    /**
     * @param  array<string, string>  $components
     */
    public function buildModule(array $components): string
    {
        $lines = [
            '/**',
            ' * Auto-generated by `parity:generate-editor-exports` from the Parity manifest.',
            ' * Do not edit manually. Run `parity:manifest` then regenerate.',
            ' */',
            '',
            "import { createExport } from '@parity/runtime';",
            '',
        ];

        foreach ($components as $slug => $exportName) {
            $lines[] = "export const {$exportName} = createExport('{$slug}');";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param  array<string, mixed>  $components
     */
    public function buildTypes(array $components): string
    {
        $lines = [
            '/**',
            ' * Auto-generated by `parity:generate-editor-exports` from the Parity manifest.',
            ' * Do not edit manually.',
            ' */',
            '',
            "import type { ComponentType } from 'react';",
            '',
        ];

        $exports = [];

        foreach ($components as $slug => $meta) {
            $exportName = is_string($meta)
                ? $meta
                : (string) ($meta['exportName'] ?? $this->exportNameFromSlug((string) $slug));
            $props = is_array($meta) ? ($meta['props'] ?? []) : [];
            $propsType = $exportName.'Props';

            $lines[] = "export type {$propsType} = {";

            foreach ($props as $prop) {
                if (! is_array($prop) || empty($prop['name'])) {
                    continue;
                }

                $optional = empty($prop['required']) ? '?' : '';
                $tsType = $this->phpTypeToTs((string) ($prop['type'] ?? 'mixed'));
                $lines[] = "    {$prop['name']}{$optional}: {$tsType};";
            }

            $lines[] = '    [key: string]: unknown;';
            $lines[] = '};';
            $lines[] = '';
            $lines[] = "export declare const {$exportName}: ComponentType<{$propsType}>;";
            $lines[] = '';

            $exports[] = $exportName;
        }

        if ($exports !== []) {
            $lines[] = 'export { '.implode(', ', $exports).' };';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function exportNameFromSlug(string $slug): string
    {
        return str_replace(' ', '', ucwords(str_replace('-', ' ', $slug)));
    }

    protected function phpTypeToTs(string $type): string
    {
        $parts = array_map('trim', explode('|', $type));
        $mapped = array_map(function (string $part) {
            return match ($part) {
                'string' => 'string',
                'int', 'integer', 'float', 'double' => 'number',
                'bool', 'boolean' => 'boolean',
                'array' => 'unknown[]',
                'null' => 'null',
                'mixed' => 'unknown',
                default => str_starts_with($part, '?')
                    ? $this->phpTypeToTs(substr($part, 1)).' | null'
                    : 'unknown',
            };
        }, $parts);

        return implode(' | ', array_unique($mapped));
    }
}
