<?php

namespace Sprout\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Sprout\Config\ConfigCollector;
use Sprout\Contracts\Host;

class SafelistCommand extends Command
{
    protected $signature = 'sprout:safelist {--output= : Output path relative to the host root}';

    protected $description = 'Extract Tailwind classes from Sprout schemas into a safelist file';

    public function handle(ConfigCollector $collector, Host $host): int
    {
        app('sprout')->rediscoverComponents();

        $classes = [];

        foreach ($collector->all() as $schema) {
            $this->extractFromSchema($schema, $classes);
        }

        $classes = array_values(array_unique(array_filter($classes)));
        sort($classes);

        $output = $this->option('output') ?? 'resources/css/_sprout-safelist.css';
        $path = $host->path($output);
        File::ensureDirectoryExists(dirname($path));

        $content = "/* Auto-generated by sprout:safelist */\n".implode("\n", array_map(
            fn ($class) => '@source inline("'.addslashes($class).'");',
            $classes
        ))."\n";

        File::put($path, $content);

        $this->components->info('Safelist written to '.$path.' ('.count($classes).' classes)');

        return self::SUCCESS;
    }

    /** @param  array<string, mixed>  $schema */
    protected function extractFromSchema(array $schema, array &$classes): void
    {
        foreach ($schema['classRules'] ?? [] as $rule) {
            if (! empty($rule['classes'])) {
                $classes = array_merge($classes, preg_split('/\s+/', $rule['classes']));
            }
        }

        foreach ($schema['matches'] ?? [] as $match) {
            if (! empty($match['preset'])) {
                $this->extractFromPreset((string) $match['preset'], $classes);
            }

            foreach ($match['cases'] ?? [] as $case) {
                foreach ($case['outcomes'] ?? [] as $outcome) {
                    if (($outcome['type'] ?? '') === 'classes' && ! empty($outcome['value'])) {
                        $classes = array_merge($classes, preg_split('/\s+/', $outcome['value']));
                    }
                }
            }

            foreach ($match['default'] ?? [] as $outcome) {
                if (($outcome['type'] ?? '') === 'classes' && ! empty($outcome['value'])) {
                    $classes = array_merge($classes, preg_split('/\s+/', $outcome['value']));
                }
            }
        }

        foreach ($schema['children'] ?? [] as $child) {
            $this->extractFromSchema($child, $classes);
        }
    }

    protected function extractFromPreset(string $presetKey, array &$classes): void
    {
        foreach ([$presetKey, "{$presetKey}Nested"] as $mapKey) {
            $map = config("sprout.presets.{$mapKey}", []);

            if (! is_array($map)) {
                continue;
            }

            $this->collectPresetClasses($map, $classes);
        }
    }

    /** @param array<mixed> $map */
    protected function collectPresetClasses(array $map, array &$classes): void
    {
        foreach ($map as $value) {
            if (is_string($value) && $value !== '') {
                $classes = array_merge($classes, preg_split('/\s+/', $value));
            } elseif (is_array($value)) {
                $this->collectPresetClasses($value, $classes);
            }
        }
    }
}
