<?php

namespace Sprout\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Sprout\Config\ConfigCollector;

class SafelistCommand extends Command
{
    protected $signature = 'sprout:safelist {--output= : Output path relative to theme root}';

    protected $description = 'Extract Tailwind classes from Sprout schemas into a safelist file';

    public function handle(ConfigCollector $collector): int
    {
        app('sprout')->discoverComponents();

        $classes = [];

        foreach ($collector->all() as $schema) {
            $this->extractFromSchema($schema, $classes);
        }

        $classes = array_values(array_unique(array_filter($classes)));
        sort($classes);

        $output = $this->option('output') ?? 'resources/css/_sprout-safelist.css';
        $path = get_theme_file_path($output);
        File::ensureDirectoryExists(dirname($path));

        $content = "/* Auto-generated by sprout:safelist */\n".implode("\n", array_map(
            fn ($class) => '@source inline("'.addslashes($class).'");',
            $classes
        ))."\n";

        File::put($path, $content);

        $this->components->info('Safelist written to '.$path.' ('.count($classes).' classes)');

        return self::SUCCESS;
    }

    /** @param array<string, mixed> $schema */
    protected function extractFromSchema(array $schema, array &$classes): void
    {
        foreach ($schema['classRules'] ?? [] as $rule) {
            if (! empty($rule['classes'])) {
                $classes = array_merge($classes, preg_split('/\s+/', $rule['classes']));
            }
        }

        foreach ($schema['matches'] ?? [] as $match) {
            foreach ($match['cases'] ?? [] as $case) {
                foreach ($case['outcomes'] ?? [] as $outcome) {
                    if (($outcome['type'] ?? '') === 'classes' && ! empty($outcome['value'])) {
                        $classes = array_merge($classes, preg_split('/\s+/', $outcome['value']));
                    }
                }
            }

            foreach ($match['default'] ?? [] as $outcome) {
                if (($outcome['type'] ?? '') === 'classes' && ! empty($outcome['value'])) {
                    $classes = array_merge($classes, preg_split('/\s+/', $outcome['value']));
                }
            }
        }

        foreach ($schema['children'] ?? [] as $child) {
            $this->extractFromSchema($child, $classes);
        }
    }
}
